# Generated by Django 4.1.3 on 2022-11-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyAndSell',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('trade_type', models.TextField(blank=True, null=True)),
                ('quantity', models.TextField(blank=True, null=True)),
                ('commulative_allocation', models.FloatField(blank=True, null=True)),
                ('balance_qty', models.FloatField(blank=True, null=True)),
                ('avg_purchase_price', models.FloatField(blank=True, null=True)),
                ('trade_price', models.FloatField(blank=True, null=True)),
                ('buy_price', models.FloatField(blank=True, null=True)),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('is_sold', models.BooleanField(blank=True, default=False, null=True)),
                ('remaining_quantity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Buy Sell manage',
            },
        ),
    ]
